sudo: require
language: node_js
git:
  submodules: false

services:
  - docker
 
env:
#  global:
#   - IMAGE_NAME=ubuntu:latest
  matrix:
    - DOCKERFILE=Dockerfile.fresh node_ver=8
    - DOCKERFILE=Dockerfile.fresh node_ver=10
#   - MIGRATION=1
#   - MIGRATION=0 UPGRADE=0
#   - MIGRATION=0 UPGRADE=1

#before_script:
#  - version="$(awk '$2 == "LOKI_LAUNCHER_VERSION" { print $3; exit }' Dockerfile)"
#  - docker pull "$IMAGE_NAME" || true

before_install:
  - docker build --build-arg MIGRATION=$MIGRATION --build-arg UPGRADE=$UPGRADE --build-arg node_ver=$node_ver -f $DOCKERFILE -t loki-project/loki-launcher .
#  - if [[ $MIGRATION ]]; then ; fi

script:
  - docker run loki-project/loki-launcher /bin/sh -c "loki-launcher status"
  - docker run loki-project/loki-launcher /bin/sh -c "loki-launcher prequal"
  - docker run loki-project/loki-launcher /bin/sh -c "loki-launcher download-binaries"
  - docker run loki-project/loki-launcher /bin/sh -c "loki-launcher start"
  - docker run loki-project/loki-launcher /bin/sh -c "loki-launcher status"
  - docker run loki-project/loki-launcher /bin/sh -c "loki-launcher stop"

#script:
#  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

#after_script:
#  - docker images
